spring:
  datasource:
    url: jdbc:mysql://${server}:3306/summer?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql_id}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver